import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router'
import { IconClose } from '@/components/icons'
import { useAuth } from '@/features/auth/auth-context'
import { listFinancialCategories } from '@/features/monthly-budget/monthly-budget-api'
import type { FinancialCategory } from '@/features/monthly-budget/domain'
import { currentMonthlyPeriod, monthlyPeriodBounds, nextMonthlyPeriod, previousMonthlyPeriod } from '@/features/monthly-budget/period'
import type { FinancialTransaction } from '@/features/transactions/domain'
import { deleteTransaction, listTransactions } from '@/features/transactions/transaction-api'
import { TransactionForm } from '@/features/transactions/transaction-form'
import { useFormatMoney } from '@/utils/format'
import { formatYearMonthLabel } from '@/utils/budget/savings-goal'

function defaultDate(period: string) { const current = currentMonthlyPeriod(); if (period !== current) return `${period}-01`; const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}` }
export function TransactionsPage() {
  const { user } = useAuth(); const format = useFormatMoney(); const [params, setParams] = useSearchParams(); const [period, setPeriod] = useState(params.get('period') ?? currentMonthlyPeriod()); const [transactions, setTransactions] = useState<FinancialTransaction[] | null>(null); const [categories, setCategories] = useState<FinancialCategory[]>([]); const [error, setError] = useState<string | null>(null); const [editing, setEditing] = useState<FinancialTransaction | null>(null); const createOpen = params.get('create') === '1'
  async function load() { setError(null); setTransactions(null); try { const bounds = monthlyPeriodBounds(period); const [rows, cats] = await Promise.all([listTransactions({ fromDate: bounds.start, toDateExclusive: bounds.endExclusive, financialCategoryId: params.get('category') ?? undefined }), listFinancialCategories(true)]); setTransactions(rows); setCategories(cats) } catch (err) { setError(err instanceof Error ? err.message : 'No se pudieron cargar las transacciones.'); setTransactions([]) } }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void Promise.resolve().then(load) }, [period])
  function close() { setEditing(null); setParams({ period }) }
  async function removeTransaction(transactionId: string) { setError(null); try { await deleteTransaction(transactionId); void load() } catch (err) { setError(err instanceof Error ? err.message : 'No se pudo eliminar la transacción.') } }
  if (!user) return null
  const categoryName = (id: string | null) => categories.find((category) => category.id === id)?.name ?? '—'
  return <div className="page"><header className="page-header row-between"><div><h1>Transacciones</h1><p className="muted">Movimientos reales del mes seleccionado.</p></div><button className="btn btn-primary" onClick={() => setParams({ period, create: '1' })}>Nueva transacción</button></header><div className="month-nav"><button className="btn" aria-label="Mes anterior" onClick={() => setPeriod(previousMonthlyPeriod(period))}>←</button><strong>{formatYearMonthLabel(period)}</strong><button className="btn" aria-label="Mes siguiente" onClick={() => setPeriod(nextMonthlyPeriod(period))}>→</button></div>{error ? <p className="field-error">{error}</p> : null}{transactions === null && !error ? <p className="page-status">Cargando transacciones…</p> : null}{transactions?.length === 0 ? <div className="empty-state stack"><p>No hay movimientos en este mes.</p><button className="btn btn-primary" onClick={() => setParams({ period, create: '1' })}>Registrar transacción</button></div> : null}{transactions?.length ? <ul className="transaction-list">{transactions.map((item) => <li key={item.id} className="card row-between"><div><strong>{item.name}</strong><p className="muted">{item.occurredOn} · {item.type === 'expense' ? categoryName(item.financialCategoryId) : 'Ingreso'}</p></div><div className="row"><strong className={item.type === 'expense' ? 'amount-expense' : 'amount-income'}>{item.type === 'expense' ? '−' : '+'}{format(item.amount)}</strong><button className="btn btn-ghost" onClick={() => setEditing(item)}>Editar</button><button className="btn btn-ghost" onClick={() => { if (window.confirm(`¿Eliminar “${item.name}”?`)) void removeTransaction(item.id) }}>Eliminar</button></div></li>)}</ul> : null}{(createOpen || editing) ? <div className="modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) close() }}><section className="modal-panel" role="dialog" aria-modal="true" aria-labelledby="transaction-form-title"><div className="modal-head"><h2 id="transaction-form-title">{editing ? 'Editar transacción' : 'Nueva transacción'}</h2><button className="btn-icon" aria-label="Cerrar" onClick={close}><IconClose /></button></div><TransactionForm userId={user.id} categories={categories} transaction={editing ?? undefined} defaultDate={defaultDate(period)} defaultCategoryId={params.get('category') ?? undefined} onCategoryCreated={(category) => setCategories((previous) => [...previous, category])} onSaved={() => { close(); void load() }} /></section></div> : null}</div>
}
